apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmmc-backend-deployment
  labels:
    app: pmmc-backend-deployment
spec:
  selector:
    matchLabels:
      app: pmmc-backend-pod
  template:
    metadata:
      labels:
        app: pmmc-backend-pod
    spec:
      containers:
        - name: pmmc-backend-container
          image: pmmcregistry.azurecr.io/pmmc-backend:latest
          envFrom:
            - configMapRef:
               name: pmmc-config
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  annotations: 
      service.beta.kubernetes.io/azure-dns-label-name: pmmc-backend-service
  name: pmmc-backend-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: pmmc-backend-pod
  type: LoadBalancer

